version: "3.7"

services:

  blueprint-web:
    build: web
    container_name: blueprint-web
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - "80:80"
    expose:
      - 8080
      - 80
